### ISSUE TITLE
Async actions?

### ISSUE THREAD

**Issue by FredyC** [modernserf/redux-action-schema#1]
I am wondering if it's possible with this module or it's meant for simple actions only? Since I don't see a way how to specify actual body of action creator function, then apparently it's not possible to return thunk. Am I missing something?

**Comment by modernserf** [comment]
Hi there -- you don't have to use the action creators as is -- you can use the actions on their own, or you can replace them with thunk-ing actions. For example:

```
schema.actionCreators.loadTodos = (dispatch) => {
    fetch("/todos")
        .then((res) => res.json())
        .then((data) => dispatch({ 
            type: schema.actions.loadTodos,
            payload: data,
        }))
}
```

I'll put together something more substantial in the `examples` directory.

**Comment by FredyC** [comment]
So you mean I first define schema with this module and then add async action creator on created object? I guess that might work, but I would to have validation of arguments for async actions too. For example in a following I would like to validate the `location` argument with schema as well.
```js
const actions = {
	lookupCityByLocation({ location }) {
		return (dispatch) => {
			this.request.findCityByIPAddress(location)
				.then((city) => dispatch(this.actions.useCity(city)))
				.catch((err) => dispatch(this.actions.handleError(err)))
			;
		};
	},
};
```

**Comment by modernserf** [comment]
It looks like you might be mixing up _actions_ and _action creators_ here -- the reducers never see a `lookupCityByLocation` action; that function dispatches a `useCity` or a `handleError` action (which the schema validates.)

I'm not sure how I would fit thunk validation into the schema independent of the actions it dispatches -- do you have any suggestions?

**Comment by FredyC** [comment]
Ok I see what you mean, yea I got that mixed up. I guess it's not necessary to have a validation for async action itself since those dispatched ones with be validated anyway, especially the one for informing about start of async action (I am missing that one in a code). Thanks for your fast response, I am going to give it a try.
