### ISSUE TITLE
Validating shape of object for actions?

### ISSUE THREAD

**Issue by FredyC** [modernserf/redux-action-schema#6]
I think that's something what is missing actually. I personally don't like positional arguments so I usually go with data wrapped into object where everything can be named. It would be nice to have ability to validate it.

I don't think you need to reinvent a wheel and implement your own validation unless you want to avoid any dependencies.

For now I think I will just grab [joi](https://www.npmjs.com/package/joi) and use it as custom validation function here, but would be nice to have it built in.

**Comment by modernserf** [comment]
It already does:
```
const schema = createSchema([
    ["addTodo", "here is a docstring",
        ["id", types.Number],
        ["text", types.String]],
])

const store = createStore(
    reducer,
    applyMiddleware(schema.createMiddleware({
        onError: (action) => console.error(action)
    })))

store.dispatch({ type: "addTodo", payload: { id: 123, text: "a string" })
// OK
store.dispatch({ type: "addTodo", payload: { id: "a string", text: 123 })
// error
```

**Comment by FredyC** [comment]
I see, well it's not very clear from current documentation. I really thought it's validating positional arguments since it's just an array. Perhaps in the section you are showing various schema forms, you could also show example of calling those action creators and what will cause error state.

**Comment by modernserf** [comment]
I've updated the docs -- let me know if that's any clearer.

**Comment by FredyC** [comment]
Definitely much better, thanks!
