### ISSUE TITLE
Bug:  "nsFunc is not a function

### ISSUE THREAD

**Issue by FredyC** [modernserf/redux-action-schema#7]
Third issue and finally it seems I found real bug :) It happens when I pass `undefined` to `namespace` option (or actually anything but string). I guess I was bit lazy as I did not want to add another check on my side as it's optional argument for me. Could you perhaps handle it more properly?

**Comment by modernserf** [comment]
OK -- `undefined` should now allow default params to pass through. Let me know if this is working as expected.

**Comment by FredyC** [comment]
I think you have misunderstood me. The `undefined` is just one of many. As I mentioned in brackets above, passing anything but string there would actually overwrite default identity function so it would fail with this error again. I think that you need to verify it's function actually.

**Comment by modernserf** [comment]
Can you write a test for this case?

**Comment by FredyC** [comment]
I am not sure about that. I think that main problem is trying to solve this with merging default values in. Once something is passed it, the `nsFunc` is set to that value no matter what it is and latter it is treated as a function. I think it needs to be more clever and in case it's not a string, it should use that default function no matter what.

**Comment by modernserf** [comment]
It's supposed to accept a either a function or a string. I could make it
throw if an invalid parameter is used?

**Comment by modernserf** [comment]
Realizing now that using a function is probably undocumented; will update
that.

**Comment by modernserf** [comment]
Ok, the namespace parameter is now documented for both functions and strings, and will throw if an invalid parameter is used.

**Comment by danielkcz** [comment]
Thanks, that should do the trick :+1:
